-- MySQL Script generated by MySQL Workbench
-- vie 29 dic 2017 10:31:23 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema biblioteca
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `biblioteca` ;

-- -----------------------------------------------------
-- Schema biblioteca
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `biblioteca` DEFAULT CHARACTER SET utf8 ;
USE `biblioteca` ;

-- -----------------------------------------------------
-- Table `biblioteca`.`Autors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`Autors` (
  `ID_Autor` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(70) NOT NULL,
  `Cognom` VARCHAR(70) NOT NULL,
  `Nacionalitat` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_Autor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`Usuaris`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`Usuaris` (
  `ID_Usuari` INT NOT NULL AUTO_INCREMENT,
  `DNI` INT NOT NULL,
  `Nom` VARCHAR(70) NOT NULL,
  `Cognom` VARCHAR(70) NOT NULL,
  `Adreca` VARCHAR(155) NOT NULL,
  `Poblacio` VARCHAR(70) NOT NULL,
  `Provincia` VARCHAR(70) NOT NULL,
  `Nacionalitat` VARCHAR(45) NULL DEFAULT NULL,
  `Adreca_electronica` VARCHAR(155) NOT NULL,
  `Telefon` INT NULL DEFAULT NULL,
  `Data_naixement` DATE NOT NULL,
  PRIMARY KEY (`ID_Usuari`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`Llibres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`Llibres` (
  `ID_Llibres` INT NOT NULL AUTO_INCREMENT,
  `Titol` VARCHAR(155) NOT NULL,
  `Numero_edicio` INT NOT NULL,
  `Lloc_publicacio` VARCHAR(70) NOT NULL,
  `Editorial` VARCHAR(70) NOT NULL,
  `Any_edicio` DATE NOT NULL,
  `ISBN` VARCHAR(45) NOT NULL,
  `Quantitat_exemplars` INT NOT NULL,
  PRIMARY KEY (`ID_Llibres`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`Exemplars`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`Exemplars` (
  `ID_Exemplar` INT NOT NULL AUTO_INCREMENT,
  `ID_Llibres` INT NOT NULL,
  PRIMARY KEY (`ID_Exemplar`),
  INDEX `ID_Llibres_idx` (`ID_Llibres` ASC),
  CONSTRAINT `ID_Llibres`
    FOREIGN KEY (`ID_Llibres`)
    REFERENCES `biblioteca`.`Llibres` (`ID_Llibres`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`Prestecs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`Prestecs` (
  `ID_Prestec` INT NOT NULL AUTO_INCREMENT,
  `Data_sortida` DATE NOT NULL,
  `Data_maxima_devolucio` DATE NOT NULL,
  `Data_real_devolucio` DATE NOT NULL,
  `Numero_prestecs` INT NOT NULL,
  `Maxim_prestecs` TINYINT NOT NULL,
  `Exemplar` INT NOT NULL,
  `Usuari` INT NOT NULL,
  PRIMARY KEY (`ID_Prestec`),
  INDEX `ID_Exemplar_idx` (`Exemplar` ASC),
  INDEX `ID_Usuari_idx` (`Usuari` ASC),
  CONSTRAINT `ID_Exemplar`
    FOREIGN KEY (`Exemplar`)
    REFERENCES `biblioteca`.`Exemplars` (`ID_Exemplar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ID_Usuari`
    FOREIGN KEY (`Usuari`)
    REFERENCES `biblioteca`.`Usuaris` (`ID_Usuari`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`Generes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`Generes` (
  `ID_Genere` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(70) NOT NULL,
  `Descripcio` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_Genere`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`Relacio_llibres_autors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`Relacio_llibres_autors` (
  `ID_Relaciola` INT NOT NULL AUTO_INCREMENT,
  `Autor` INT NOT NULL,
  `Llibres` INT NOT NULL,
  PRIMARY KEY (`ID_Relaciola`),
  INDEX `ID_Llibre_idx` (`Llibres` ASC),
  INDEX `Autor_idx` (`Autor` ASC),
  CONSTRAINT `Autor`
    FOREIGN KEY (`Autor`)
    REFERENCES `biblioteca`.`Autors` (`ID_Autor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ID_Llibre`
    FOREIGN KEY (`Llibres`)
    REFERENCES `biblioteca`.`Llibres` (`ID_Llibres`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`Relacio_llibres_generes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`Relacio_llibres_generes` (
  `ID_Relaciolg` INT NOT NULL AUTO_INCREMENT,
  `Llibres` INT NOT NULL,
  `Genere` INT NOT NULL,
  PRIMARY KEY (`ID_Relaciolg`),
  INDEX `ID_Genere_idx` (`Genere` ASC),
  INDEX `ID_Llibre_idx` (`Llibres` ASC),
  CONSTRAINT `ID_Lli`
    FOREIGN KEY (`Llibres`)
    REFERENCES `biblioteca`.`Llibres` (`ID_Llibres`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ID_Gen`
    FOREIGN KEY (`Genere`)
    REFERENCES `biblioteca`.`Generes` (`ID_Genere`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `biblioteca`.`Autors`
-- -----------------------------------------------------
START TRANSACTION;
USE `biblioteca`;
INSERT INTO `biblioteca`.`Autors` (`ID_Autor`, `Nom`, `Cognom`, `Nacionalitat`) VALUES (DEFAULT, 'Juanillo', 'Elwriter', 'Espanya');
INSERT INTO `biblioteca`.`Autors` (`ID_Autor`, `Nom`, `Cognom`, `Nacionalitat`) VALUES (DEFAULT, 'Pepita', 'Pensamas', 'Espanya');
INSERT INTO `biblioteca`.`Autors` (`ID_Autor`, `Nom`, `Cognom`, `Nacionalitat`) VALUES (DEFAULT, 'Gatuna', 'Loca de Losgatos', 'Espanya');

COMMIT;


-- -----------------------------------------------------
-- Data for table `biblioteca`.`Usuaris`
-- -----------------------------------------------------
START TRANSACTION;
USE `biblioteca`;
INSERT INTO `biblioteca`.`Usuaris` (`ID_Usuari`, `DNI`, `Nom`, `Cognom`, `Adreca`, `Poblacio`, `Provincia`, `Nacionalitat`, `Adreca_electronica`, `Telefon`, `Data_naixement`) VALUES (DEFAULT, 44444444, 'Pepe', 'Pepin', 'Pepi 2', 'Tortosa', 'Tarragona', 'España', 'pepe@pepe.com', 655555555, '1987-02-25');
INSERT INTO `biblioteca`.`Usuaris` (`ID_Usuari`, `DNI`, `Nom`, `Cognom`, `Adreca`, `Poblacio`, `Provincia`, `Nacionalitat`, `Adreca_electronica`, `Telefon`, `Data_naixement`) VALUES (DEFAULT, 44444446, 'Friki', 'Molt', 'Frikitriki 21', 'Amposta', 'Tarragona', 'España', 'friki@friki.com', 655555560, '1992-06-12');
INSERT INTO `biblioteca`.`Usuaris` (`ID_Usuari`, `DNI`, `Nom`, `Cognom`, `Adreca`, `Poblacio`, `Provincia`, `Nacionalitat`, `Adreca_electronica`, `Telefon`, `Data_naixement`) VALUES (DEFAULT, 44444447, 'Maica', 'Modli', 'Pepertin 1', 'Godall', 'Tarragona', 'España', 'maica@maica.com', 655555587, '1972-10-03');
INSERT INTO `biblioteca`.`Usuaris` (`ID_Usuari`, `DNI`, `Nom`, `Cognom`, `Adreca`, `Poblacio`, `Provincia`, `Nacionalitat`, `Adreca_electronica`, `Telefon`, `Data_naixement`) VALUES (DEFAULT, 44444425, 'Nelson', 'Pipintela', 'Teo Gon 12', 'Deltebre', 'Tarragona', 'España', 'nelson@nelson.com', 655555545, '1988-08-24');

COMMIT;


-- -----------------------------------------------------
-- Data for table `biblioteca`.`Llibres`
-- -----------------------------------------------------
START TRANSACTION;
USE `biblioteca`;
INSERT INTO `biblioteca`.`Llibres` (`ID_Llibres`, `Titol`, `Numero_edicio`, `Lloc_publicacio`, `Editorial`, `Any_edicio`, `ISBN`, `Quantitat_exemplars`) VALUES (DEFAULT, 'El pensador de Sheschfield', 1, 'Tortosa', 'Lllegeixmes', '1995-05-16', 'ISBN-10: 1521996024', 12);
INSERT INTO `biblioteca`.`Llibres` (`ID_Llibres`, `Titol`, `Numero_edicio`, `Lloc_publicacio`, `Editorial`, `Any_edicio`, `ISBN`, `Quantitat_exemplars`) VALUES (DEFAULT, 'Monos a la vista', 2, 'Tortosa', 'Llegeixmes', '2001-02-21', 'ISBN-10: 1521996025', 8);
INSERT INTO `biblioteca`.`Llibres` (`ID_Llibres`, `Titol`, `Numero_edicio`, `Lloc_publicacio`, `Editorial`, `Any_edicio`, `ISBN`, `Quantitat_exemplars`) VALUES (DEFAULT, 'Filosopensant', 12, 'Tortosa', 'Llegir i pensant', '2016-08-24', 'ISBN-10: 1521996032', 21);
INSERT INTO `biblioteca`.`Llibres` (`ID_Llibres`, `Titol`, `Numero_edicio`, `Lloc_publicacio`, `Editorial`, `Any_edicio`, `ISBN`, `Quantitat_exemplars`) VALUES (DEFAULT, 'Gatets', 1, 'Tortosa', 'Animalons', '2015-05-14', 'ISBN-10: 1521836024', 30);

COMMIT;


-- -----------------------------------------------------
-- Data for table `biblioteca`.`Exemplars`
-- -----------------------------------------------------
START TRANSACTION;
USE `biblioteca`;
INSERT INTO `biblioteca`.`Exemplars` (`ID_Exemplar`, `ID_Llibres`) VALUES (DEFAULT, 1);
INSERT INTO `biblioteca`.`Exemplars` (`ID_Exemplar`, `ID_Llibres`) VALUES (DEFAULT, 2);
INSERT INTO `biblioteca`.`Exemplars` (`ID_Exemplar`, `ID_Llibres`) VALUES (DEFAULT, 3);
INSERT INTO `biblioteca`.`Exemplars` (`ID_Exemplar`, `ID_Llibres`) VALUES (DEFAULT, 4);

COMMIT;


-- -----------------------------------------------------
-- Data for table `biblioteca`.`Generes`
-- -----------------------------------------------------
START TRANSACTION;
USE `biblioteca`;
INSERT INTO `biblioteca`.`Generes` (`ID_Genere`, `Nom`, `Descripcio`) VALUES (DEFAULT, 'Drama', 'Lorem ipsum dolor drama amet');
INSERT INTO `biblioteca`.`Generes` (`ID_Genere`, `Nom`, `Descripcio`) VALUES (DEFAULT, 'Animals', 'Lorem ipusm dolor animals amet');

COMMIT;


-- -----------------------------------------------------
-- Data for table `biblioteca`.`Relacio_llibres_autors`
-- -----------------------------------------------------
START TRANSACTION;
USE `biblioteca`;
INSERT INTO `biblioteca`.`Relacio_llibres_autors` (`ID_Relaciola`, `Autor`, `Llibres`) VALUES (DEFAULT, 1, 1);
INSERT INTO `biblioteca`.`Relacio_llibres_autors` (`ID_Relaciola`, `Autor`, `Llibres`) VALUES (DEFAULT, 1, 2);
INSERT INTO `biblioteca`.`Relacio_llibres_autors` (`ID_Relaciola`, `Autor`, `Llibres`) VALUES (DEFAULT, 2, 3);
INSERT INTO `biblioteca`.`Relacio_llibres_autors` (`ID_Relaciola`, `Autor`, `Llibres`) VALUES (DEFAULT, 3, 4);

COMMIT;


-- -----------------------------------------------------
-- Data for table `biblioteca`.`Relacio_llibres_generes`
-- -----------------------------------------------------
START TRANSACTION;
USE `biblioteca`;
INSERT INTO `biblioteca`.`Relacio_llibres_generes` (`ID_Relaciolg`, `Llibres`, `Genere`) VALUES (DEFAULT, 1, 1);
INSERT INTO `biblioteca`.`Relacio_llibres_generes` (`ID_Relaciolg`, `Llibres`, `Genere`) VALUES (DEFAULT, 2, 1);
INSERT INTO `biblioteca`.`Relacio_llibres_generes` (`ID_Relaciolg`, `Llibres`, `Genere`) VALUES (DEFAULT, 3, 1);
INSERT INTO `biblioteca`.`Relacio_llibres_generes` (`ID_Relaciolg`, `Llibres`, `Genere`) VALUES (DEFAULT, 4, 2);

COMMIT;

